### ISSUE TITLE
D-Pointer work breaks views

### ISSUE THREAD

**Issue by riyad** [kelvie/basket#1]
Commit de157149cafaa6cea93285751d6c56c939bd234b breaks the basket item views.
The item view is blank.
But the new item position indicator is where it would be when the items would be correctly drawn (but it is shown permanently).
You can add new items and the indicator will move further down.
Right clicking in the area where the actual items should be gives you the menu you will see when right clicking in the empty area.

I hope this helps.

Cheers, Riyad

**Comment by kozzzlov** [comment]
Hi Kelvie!
I confirm the same on Mandriva 2010 64bit. If you need my help to test - just let me know.
Thanks,
Kirill

**Comment by riyad** [comment]
This bug got fixed in 726f8196f16324e7600f56958f3372ce3039b3fa .

**Comment by kozzzlov** [comment]
Hi Riyad!

Thank you very much! I've tested it on Mandriva 2010 64 bit - all is looking fine except Alt-Down, Alt-Up shortcuts. They are not working.

Regards,
Kirill

**Comment by riyad** [comment]
Thanks for the info, but it seems to work for me.
Can you open a new issue and describe the (mis)behaviour in a little more detail?
Regards, Riyad

**Comment by kozzzlov** [comment]
OK I will do.
Regards,
Kirill
